"use client"
import Link from "next/link"
import { Eye, Pencil, Trash2 } from "lucide-react"
import { deleteCustomer } from "@/actions/customer"
import { useRouter } from "next/navigation"
import type { CustomerStatus } from "@prisma/client"

export interface CustomerListItem { id: number; fullName: string; email: string; phone: string; totalOrders: number; totalSpent: number; status: CustomerStatus }
export default function CustomerTable({ customers }: { customers: CustomerListItem[] }) { const router = useRouter(); async function removeCustomer(id: number) { if (!window.confirm("Are you sure you want to delete this customer?")) return; try { await deleteCustomer(id); router.refresh() } catch (error) { window.alert(error instanceof Error ? error.message : "Unable to delete customer.") } }
return <div className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead className="bg-muted/50"><tr><th className="px-4 py-3 text-left">Name</th><th className="px-4 py-3 text-left">Email</th><th className="px-4 py-3 text-left">Phone</th><th className="px-4 py-3 text-left">Orders</th><th className="px-4 py-3 text-left">Total Spent</th><th className="px-4 py-3 text-left">Status</th><th className="px-4 py-3 text-center">Actions</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id} className="border-t hover:bg-muted/30"><td className="px-4 py-4 font-medium">{customer.fullName}</td><td className="px-4 py-4">{customer.email}</td><td className="px-4 py-4">{customer.phone}</td><td className="px-4 py-4">{customer.totalOrders}</td><td className="px-4 py-4 font-semibold">${customer.totalSpent.toFixed(2)}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${customer.status === "ACTIVE" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700"}`}>{customer.status === "ACTIVE" ? "Active" : "Inactive"}</span></td><td className="px-4 py-4"><div className="flex justify-center gap-2"><Link href={`/admin/customers/${customer.id}`} className="rounded-md p-2 hover:bg-blue-100"><Eye size={18} /></Link><Link href={`/admin/customers/${customer.id}/edit`} className="rounded-md p-2 hover:bg-amber-100"><Pencil size={18} /></Link><button type="button" onClick={() => removeCustomer(customer.id)} className="rounded-md p-2 hover:bg-red-100"><Trash2 size={18} /></button></div></td></tr>)}</tbody></table></div>{customers.length === 0 && <p className="p-10 text-center text-muted-foreground">No customers found.</p>}</div> }
